"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_for_scitex_linalg_reports_no_violations():
    # Arrange
    if shutil.which("scitex-dev") is None:
        import pytest as _pt
        _pt.importorskip(
            "scitex_dev",
            reason="scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]",
        )
    from scitex_dev.testing import audit_all_for_package

    # Act
    result = audit_all_for_package('scitex-linalg')
    # Assert
    assert result is None or result == 0
